#!/bin/sh
# coding=utf-8
# vim:et ts=4 sts=4 sw=4
#
# ibus-wbjj - 五笔加加Plus for IBus
#
# Copyright (c) ibus-table 2008-2009 Yu Yuwei <acevery@gmail.com>
# Copyright (c) 2013-2022 LI Yunfei <yanzilisan183@sina.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#

prefix=/usr
exec_prefix=${prefix}
datarootdir=${prefix}/share
export IBUS_PREFIX=/usr
export IBUS_DATAROOTDIR=${prefix}/share
export IBUS_LOCALEDIR=${datarootdir}/locale
cd /usr/share/ibus-wbjj/engine
exec /usr/bin/python3 setup.py $@

